operators:
  label: "Operators"
  parameters:
    - name: "Cluster Embeddings"
      type: "cluster_embeddings"
      parameters: { index_name: "video" }
    - name: "Video Vector Representation"
      type: "vid_vec_rep_clip"
      parameters: { index_name: "video" }