name: Operator Tests

on:
  pull_request:
    paths:
      - 'feluda/operators/**'
      - '.github/workflows/operator-tests.yml'

jobs:
  test-operators:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Get modified files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: |
            feluda/operators/**/*.py
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest
      - name: Run tests for modified operators
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Modified operator files:"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file"
            if [[ $file == feluda/operators/* ]]; then
              operator_name=$(basename "$file" .py)
              test_path="tests/operators/test_${operator_name}.py"
              if [ -f "$test_path" ]; then
                echo "Running tests for $operator_name"
                python -m pytest "$test_path" -v
              fi
            fi
          done
      - name: Cleanup
        if: always()
        run: |
          rm -rf ~/.cache/feluda
          rm -rf ~/.cache/pip
          rm -rf /tmp/feluda*
          find . -type d -name "__pycache__" -exec rm -r {} +
